/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hello */

#ifndef _Included_com_hello
#define _Included_com_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hello
 * Method:    DisplayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hello_DisplayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
