/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ocr_java */

#ifndef _Included_com_ocr_java
#define _Included_com_ocr_java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ocr_java
 * Method:    OcrTesseract
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ocr_1java_OcrTesseract
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
